Pig Stack Trace
---------------
ERROR 6000: 
<file estimate_unode4.pig, line 15, column 0> Output Location Validation Failed for: '/tmp/estimate_12_unode5_Raw_stat More info to follow:
Output directory /tmp/estimate_12_unode5_Raw_stat already exists

org.apache.pig.impl.plan.VisitorException: ERROR 6000: 
<file estimate_unode4.pig, line 15, column 0> Output Location Validation Failed for: '/tmp/estimate_12_unode5_Raw_stat More info to follow:
Output directory /tmp/estimate_12_unode5_Raw_stat already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:95)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:77)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:45)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:298)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1360)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1297)
	at org.apache.pig.PigServer.execute(PigServer.java:1289)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:360)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:131)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:192)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:164)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
	at org.apache.pig.Main.run(Main.java:561)
	at org.apache.pig.Main.main(Main.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory /tmp/estimate_12_unode5_Raw_stat already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:132)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:80)
	... 26 more
================================================================================
